#Intro
Intro_Tavern_Elrick = u"¿Qué os parece? ¿Trabajaremos juntos?"
Intro_Tavern_Alida = u"¿Pero si todos superamos las pruebas, quien se casara con la princesa?"
Harek = u"Supongo que la princesa se casará con quién más le guste"
Elrick = u"Sería lo más inteligente. Utilizar las pruebas para conocernos y ver nuestras virtudes, especialmente las mias, para elegir depués quien más le guste."
Alida = u"Te veo muy seguro de tus posibilidades"
Elrick = u"Seguro que la princesa busca un pretendiente inteligente que sepa tomar buenas decisiones. Y si además es chico guapo, mejor"
Harek = u"Puede que yo no sea muy guapo, pero si la princesa Melisenda me escogiera a mí me deviviría por hacerla sentir como una reina"
Alida = u"Eso es realmente hermoso, Harek. Pero cuando Melisenda regente Sapiensa necesitará a su lado alguien que se preocupe por el reino y sepa hacerlo prosperar"
Sullx = u"Elrick será un buen soberano, ya dirigimos hace años un ejercito de zombis"
Alida = u"¡Sapiensa no es un reino bélico! Hace tiempo que estamos en paz y no creo que nadie quiera que eso cambie."
Elrick = u"Sullx habla del pasado, yo tampoco quiero que se acabe la paz en Sapiensa"
Harek = u"Nada de guerra en Sapiensa"
Alida = u"Bien, parece que empezamos a entendernos. ¿Que hacemos para superar las pruebas?"
Elrick = u"..."
Harek = u"..."
Sullx = u"Yo conozco a una tarotixta, lo mismo ella nos da alguna pista"
Harek = u"¡Eso es una buena idea! Además seguro que tiene un gato negro. Me encantan los gatos."
Alida = u"Los gatos son más típicos de la brujas."
Elrick = u"Pero creo que ya no sigue adivinando, que ahora se dedica a la respostería"
Harek = u"¡Oh! ¿Es la mujer que vende galletitas de la fortuna?"
Elrick = u"¡Esa! ¿Habeís probado las bambas? Yo cuando llevo bien la línea me permito desayunar alguna. ¡Están de muerte!"
# transición para dialogo de puzles
Puzles = u"Seguramente os preguntareís como alguien tan prometedor como yo a acabado ayudando a un bárbaro amante de los gatos, a un nigromante con delirios de grandeza y a una cazadora disfrazada de hombrea conseguir el corazón de una princesa."
Puzles = u"Mi nombre es HADOKEN Puzles y esta es mi historia."