# pastoreo:
Puzles = u"¿Vosotros quereis la mano de la princesa o estais de paso?"
Harek = u"Claro que queremos la mano de la princesa, Pusles. Pero no somos unos genios y no sabemos que tenemos que hacer"
Elrick = u"Hemos oido que la princesa ha elaborado tres pruebas, pero no ha puesto donde será la primera"
Alida = u"Llevamos buscando pistas varios días, pero no hemos descubierto nada. Habíamos decidido formar equipo para aumentar nuestras posibilidades de exito. Hace un momento intentabamos pensar en una solución, pero nada."
Puzles = u"Vale, escuchad, haremos lo siguiente. Os voy a ayudar. La primera prueba consiste en una competición de pastoreo"
Sullx = u"Elrick no sabe pastorear"
Harek = u"Yo tampoco, ¿No podía ser de cuidar gatitos?"
Alida = u"O de cazar las ovejas, sé hacerlo sin que sufran ningún daño."
Puzles = u"No, es una competición de pastoreo. El que lo haga mejor conseguirá el favor de la princesa"
Elrick = u"¿Entonces sólo necesitamos un grupo de ovejas que pastorear?"
Puzles = u"Y un animal al que entrenar"
Harek = u"¿Vale cualquiera? Entonces prepararé a guantes. Es una ricura de gato y seguro que con un par de lecciones sabe pastorear"
Elrick = u"Yo entrenaré a mi viejo perro rudy, bastará con revivirlo y adiestrarlo un poco para ganar la competición. Pusles, confiamos en tí para conseguirnos un buen rebaño que pastorear"
Narrador = "Harek y Elrick salen del local"
Puzles = "¿Qué? ¿Por qué tengo que encargarme yo de eso? Espera... ¿Han dicho gato pastor y perro zombi?"
Alida = u"..."
Puzles = u"¿Qué he hecho para merecer esto?"
Alida = u"La verdad es que me estaba preguntando porque has decidido ayudarnos"
Puzles = u"Digamos que tengo cierto interés en que la princesa Melisenda encuentra pronto marido."
Puzles = u"Oh bueno, también me vale si encuentra mujer"
Alida = u"¿Qué insinuas?"
Puzles = u"Pues... Si la princesa Melisenda te escogiera a tí como su prometida, seríais mujer y mujer."
Alida = u"¡Estás asumiendo mi género! ¡Soy un hombre y me llamo Alido!"
Puzles = u"..."
Alida = u"¡Me voy a buscar un animal para la competición!"
# Y se va
Puzles = u"¿Por qué a mi?"
